var sheetJS = [{"First":"Alicia ","Last":"Cohen","Company":"Alicia Cohen","Type of Vendor":"Paintings","Email address":"","Type":"","Booth":"R-20"},
{"First":"","Last":"","Company":"Alfalfa Farms","Type of Vendor":"Winery","Email address":"-","Type":"-","Booth":"Food-1"},
{"First":"Melynn","Last":"Allen","Company":"Allen Design Studio","Type of Vendor":"Ceramic work ","Email address":"allendesignstudio@verizon.net","Type":"Returning","Booth":"T-2"},
{"First":"Janis","Last":"Anderson","Company":"AnnaJanessa PhotoArt","Type of Vendor":"Photography","Email address":"","Type":"","Booth":"R-9"},
{"First":"Egmar","Last":"Alper","Company":"Atena Luminaire","Type of Vendor":"wax luminaries","Email address":"atenaluminaire@gmail.com","Type":"New","Booth":"T-23"},
{"First":"Joe & Jan","Last":"Salamone","Company":"Beach Walker Studio","Type of Vendor":"Jewelry","Email address":"beachwalkerstudio@yahoo.com","Type":"Returning","Booth":"T-9"},
{"First":"Becky ","Last":"Williams","Company":"Becky Williams","Type of Vendor":"Jewelry, handpainted scarfs","Email address":"","Type":"","Booth":"M-2"},
{"First":"","Last":"","Company":"Beer Garden","Type of Vendor":"Concession","Email address":"","Type":"","Booth":"Beer"},
{"First":"Judy","Last":"Heinrich","Company":"Bent N Beaded","Type of Vendor":"Beaded items","Email address":"jujuheath919@gmail.com","Type":"New","Booth":"M-12"},
{"First":"Betsy","Last":"Frost","Company":"Betsy Frost","Type of Vendor":"Sterling silver jewelry","Email address":"betsyfrostdesign@comcast.net","Type":"Returning","Booth":"R-11"},
{"First":"Bill","Last":"Spaulding","Company":"Bill Spaulding","Type of Vendor":"Pottery","Email address":"arunshardpottery@yahoo.com","Type":"Returning","Booth":"M-22"},
{"First":"Billy","Last":"Laforme","Company":"Billy Laforme","Type of Vendor":"Photography","Email address":"","Type":"","Booth":"T-21"},
{"First":"Bobbie","Last":"Bush","Company":"Bobbie Bush Photography","Type of Vendor":"Photography","Email address":"bobbie@bobbiebush.com","Type":"Returning","Booth":"T-5"},
{"First":"Nancy","Last":"Klebart","Company":"Buy the Sea","Type of Vendor":"Seaglass","Email address":"","Type":"","Booth":"R-19"},
{"First":"Lynn","Last":"Hildenbrand","Company":"Cannoli's","Type of Vendor":"Cannoli's","Email address":"","Type":"","Booth":"Food-5"},
{"First":"Sheri","Last":"Levine","Company":"Can't Resist Pillows","Type of Vendor":"Toss pillows","Email address":"cantresistgifts@aol.com","Type":"Returning","Booth":"M-4"},
{"First":"Carol","Last":"Mortimore","Company":"Carol Mortimore","Type of Vendor":"Books, sachets","Email address":"","Type":"","Booth":"T-17"},
{"First":"Carol","Last":"Stremple","Company":"Carol Stremble","Type of Vendor":"Jewelry/sculptures","Email address":"clstrem@zoominternet.net","Type":"New","Booth":"T-18"},
{"First":"Caroline","Last":"Goodrich","Company":"Caroline Goodrich","Type of Vendor":"Bags, accessories, paintings","Email address":"","Type":"","Booth":"S-15"},
{"First":"Catherine","Last":"Angelson","Company":"Catherine Angelson","Type of Vendor":"Jewelry","Email address":"cangelson@msn.com","Type":"Returning","Booth":"R-10"},
{"First":"Buffy","Last":"Cave","Company":"Cave Studio Arts","Type of Vendor":"Jewelry","Email address":"cavestudioarts@gmail.com","Type":"Returning","Booth":"M-32"},
{"First":"","Last":"","Company":"Chamber of Commerce","Type of Vendor":"Cape Ann License Plate!","Email address":"","Type":"","Booth":"M-35"},
{"First":"","Last":"","Company":"Copperdome Crust","Type of Vendor":"Pizza","Email address":"-","Type":"-","Booth":"Food-4"},
{"First":"Beth","Last":"McKinney","Company":"Copper Moon Studio","Type of Vendor":"Jewelry","Email address":"coppermoonstudio@comcast.net","Type":"New","Booth":"M-25"},
{"First":"Courtney","Last":"Kelly","Company":"Courtney Kelly","Type of Vendor":"Oil paintings, cigar boxes","Email address":"crumbough@gmail.com","Type":"Returning","Booth":"S-8"},
{"First":"Robin","Last":"Foudray","Company":"Creative Spirit Design","Type of Vendor":"Beachstone jewelry","Email address":"beadedaccents@yahoo.com","Type":"New","Booth":"M-6"},
{"First":"Jean","Last":"Davis","Company":"Crystal Energy Images","Type of Vendor":"Crystal photos","Email address":"","Type":"","Booth":"R-2"},
{"First":"James","Last":"Sousa","Company":"Crystal Lake Editions","Type of Vendor":"Fine art photography","Email address":"james.sousa@comcast.net","Type":"New","Booth":"R-3"},
{"First":"Deborah","Last":"MacFail","Company":"Deborah MacFail","Type of Vendor":"Jewelry","Email address":"dmacfail@hotmail.com","Type":"Returning","Booth":"T-6"},
{"First":"Melissa","Last":"Tarr","Company":"Design of Mine","Type of Vendor":"Repurposed vintage jewelry","Email address":"designofmine66@gmail.com","Type":"Returning","Booth":"S-13"},
{"First":"Anke","Last":"Ueckert","Company":"Designs by Anke","Type of Vendor":"Jewelry","Email address":"ankeueckert@yahoo.com","Type":"Returning","Booth":"M-3"},
{"First":"Elizabeth","Last":"Daugherty","Company":"Elizabeth Daugherty","Type of Vendor":"Cutting boards, lamps","Email address":"EBDesign@mail.com","Type":"Returning","Booth":"M-26"},
{"First":"Ellen ","Last":"Garvey","Company":"Ellen Garvey","Type of Vendor":"Glass blowing","Email address":"","Type":"","Booth":"M-33"},
{"First":"Emily","Last":"Benincasa","Company":"Emily Benincasa","Type of Vendor":"Pottery","Email address":"emilybenincasa@gmail.com","Type":"New","Booth":"M-11"},
{"First":"Emily ","Last":"Hammond","Company":"Emily Hammond","Type of Vendor":"Crotcheted dolls","Email address":"","Type":"","Booth":"M-39"},
{"First":"Erin","Last":"Cherry","Company":"Erin Cherry","Type of Vendor":"Assorted items","Email address":"erinwcherry@gmail.com","Type":"New","Booth":"R-5"},
{"First":"Joe","Last":"Higgins","Company":"Fished Impressions","Type of Vendor":"Fish prints","Email address":"","Type":"","Booth":"M-9"},
{"First":"Jennifer","Last":"Falconer","Company":"Found Objects","Type of Vendor":"Assorted items","Email address":"","Type":"","Booth":"S-12"},
{"First":"Fred","Last":"Moreau","Company":"Fred Moreau","Type of Vendor":"Sand art for kids","Email address":"svbdirector2@yahoo.com","Type":"Returning","Booth":"M-37"},
{"First":"","Last":"","Company":"Gazebo Music Stage","Type of Vendor":"Live music","Email address":"-","Type":"-","Booth":"Gazebo Music Stage"},
{"First":"-","Last":"-","Company":"Girl Scouts","Type of Vendor":"Community information","Email address":"","Type":"","Booth":"M-42"},
{"First":"Heather","Last":"Kidson","Company":"Heather Kidson","Type of Vendor":"Painted silk clothing","Email address":"","Type":"","Booth":"M-40"},
{"First":"Pamela","Last":"Morss","Company":"Heather Outlaw Designs","Type of Vendor":"Jewelry","Email address":"pamelamorss@comcast.net","Type":"Returning","Booth":"M-31"},
{"First":"Holly","Last":"Young","Company":"Holly Young","Type of Vendor":"Landscape artist, fine arts & plates","Email address":"","Type":"","Booth":"S-7"},
{"First":"Jacqueline","Last":"Bokor","Company":"Jacqueline Bokor","Type of Vendor":"Jewelry","Email address":"","Type":"","Booth":"R-21"},
{"First":"Jan & Joe","Last":"Lamb","Company":"Jan's Fun Knits","Type of Vendor":"Crotcheted Items ","Email address":"","Type":"","Booth":"M-27"},
{"First":"Jennifer","Last":"Hoffman","Company":"Jennifer's Handmade Soap","Type of Vendor":"Soap","Email address":"","Type":"","Booth":"M-8"},
{"First":"Jennifer","Last":"Zhang","Company":"Jennifer Zhang","Type of Vendor":"Origami","Email address":"","Type":"","Booth":"M-43"},
{"First":"Jess","Last":"Hartley","Company":"Jess Hartley","Type of Vendor":"Abstract painting","Email address":"","Type":"","Booth":"T-4"},
{"First":"Jill","Last":"Hamilton","Company":"Jill Hamilton","Type of Vendor":"Jewelry","Email address":"","Type":"","Booth":"R-17"},
{"First":"Jodi","Last":"Blagden","Company":"Jodi Blagden","Type of Vendor":"Fine art","Email address":"","Type":"","Booth":"T-20"},
{"First":"Judy","Last":"Serafini","Company":"Judy Serafini","Type of Vendor":"Jewelry","Email address":"","Type":"","Booth":"M-41"},
{"First":"Karol","Last":"Peralta","Company":"Karol Peralta","Type of Vendor":"Jewelry","Email address":"kgartdeco@comcast.net","Type":"Returning","Booth":"S-11"},
{"First":"Katrina","Last":"Abbott","Company":"Katrina Abbott","Type of Vendor":"Paintings/Collages","Email address":"ksabbott@comcast.net","Type":"Returning","Booth":"T-1"},
{"First":"Keri","Last":"Gaven","Company":"Keri Gaven","Type of Vendor":"Photography","Email address":"","Type":"","Booth":"M-36"},
{"First":"Kerry","Last":"Halley-Skelton","Company":"Kerry Halley-Skelton","Type of Vendor":"Acrylic paintings","Email address":"kerryh327@comcast.net","Type":"New","Booth":"T-10"},
{"First":"Kiki","Last":"Kinney","Company":"Kiki Kinney","Type of Vendor":"Assorted items","Email address":"","Type":"","Booth":"M-13"},
{"First":"Jennifer","Last":"Hickman","Company":"Kittredge Candles","Type of Vendor":"Candles/soaps/lotions","Email address":"kittredgecandles@comcast.net","Type":"Returning","Booth":"M-1"},
{"First":"Melissa","Last":"Rioux","Company":"Lakonia Greek Products","Type of Vendor":"Assorted items","Email address":"info@lakoniagreekproducts.com","Type":"New","Booth":"M-30"},
{"First":"Greg","Last":"Blagden","Company":"Life by the Sea","Type of Vendor":"Clothing Merchandise","Email address":"","Type":"","Booth":"M-44"},
{"First":"Lisa","Last":"Knebel","Company":"Lisa Knebel","Type of Vendor":"Pottery","Email address":"","Type":"","Booth":"T-11"},
{"First":"Dean","Last":"DiMarzo","Company":"Lucky Fish Studio","Type of Vendor":"Painting ","Email address":"dimarzos@aol.com","Type":"Returning","Booth":"T-8"},
{"First":"Lyell","Last":"Castonguay","Company":"Lyell Castonguay DBA Woodcut","Type of Vendor":"Wood carving prints","Email address":"lyellcastonguay@gmail.com","Type":"New","Booth":"M-24"},
{"First":"Myron","Last":"Lapine","Company":"Ma & Pa's Pickles, Etc.","Type of Vendor":"Pickles!","Email address":"","Type":"","Booth":"M-15"},
{"First":"Margaret","Last":"Miller","Company":"Margaret Miller","Type of Vendor":"Watercolors, printmaking","Email address":"","Type":"","Booth":"T-15"},
{"First":"Marie","Last":"Pisaturo","Company":"Marie Pisaturo","Type of Vendor":"Assorted items","Email address":"MP_athome@yahoo.com","Type":"New","Booth":"M-29"},
{"First":"","Last":"","Company":"Markouk Bread","Type of Vendor":"Flatbread Sandwiches","Email address":"-","Type":"-","Booth":"Food-3"},
{"First":"Martha","Last":"Everson","Company":"Martha Everson Studio","Type of Vendor":"Paint, photography, digital","Email address":"martha@marthaeverson.com","Type":"Returning","Booth":"T-13"},
{"First":"Mary","Last":"Bowles","Company":"Mary Bowles Shell Design","Type of Vendor":"Shell design","Email address":"","Type":"","Booth":"R-16"},
{"First":"Maureen","Last":"McKinnon","Company":"Maureen McKinnon","Type of Vendor":"Floral designs","Email address":"","Type":"","Booth":"T-24"},
{"First":"Meghan","Last":"Daly","Company":"Meghan Isms","Type of Vendor":"Art, paintings, sculptures","Email address":"","Type":"","Booth":"R-6"},
{"First":"Monique","Last":"Sousa","Company":"Monique Sousa","Type of Vendor":"Jewelry","Email address":"dutchsousa@cox.net","Type":"New","Booth":"M-16"},
{"First":"Tracy","Last":"Emanuel","Company":"Near Perfect Design","Type of Vendor":"Bracelets, belt buckles","Email address":"","Type":"","Booth":"M-7"},
{"First":"Kat","Last":"Masella","Company":"Northeast Art","Type of Vendor":"Assorted items","Email address":"","Type":"","Booth":"T-14"},
{"First":"Betsy","Last":"Vicksell","Company":"On the Horizon","Type of Vendor":"Clay/glass art","Email address":"bvicksell@verizon.net","Type":"Returning","Booth":"M-19"},
{"First":"Sarah","Last":"Grow","Company":"Open Door","Type of Vendor":"Non-profit","Email address":"sarah@foodpantry.org","Type":"Returning","Booth":"M-34"},
{"First":"Pamela","Last":"Kubbins","Company":"Pam's Pashminas & Exotic Scarfs","Type of Vendor":"Scarfs & Shawls","Email address":"","Type":"","Booth":"T-12"},
{"First":"Patricia","Last":"Baker","Company":"Patricia Baker","Type of Vendor":"Hand woven Nantucket baskets","Email address":"patricia432@earthlink.com","Type":"Returning","Booth":"M-10"},
{"First":"Patricia","Last":"Doherty","Company":"Patricia Doherty","Type of Vendor":"Oil paintings","Email address":"dohertypandt@aol.com","Type":"Returning","Booth":"R-7"},
{"First":"Patrick","Last":"Horgan","Company":"Phat Phish","Type of Vendor":"Fish Prints","Email address":"","Type":"","Booth":"T-25"},
{"First":"Pauline","Last":"Nelson","Company":"Penny Poppers","Type of Vendor":"Glass beaded jewlery","Email address":"pennypopperbeads@gmail.com","Type":"Returning","Booth":"S-14"},
{"First":"Peggy","Last":"Ricker","Company":"Peggy Ricker","Type of Vendor":"Driftwood signs","Email address":"","Type":"","Booth":"R-18"},
{"First":"Susan","Last":"Gaboriault","Company":"Pinderella","Type of Vendor":"Acrylic pins ","Email address":"pinderellanh@yahoo.com","Type":"New","Booth":"R-13"},
{"First":"Kristen","Last":"Williams","Company":"ReSailed Bags","Type of Vendor":"Bags","Email address":"","Type":"","Booth":"R-15"},
{"First":"Robert ","Last":"Hahn","Company":"Robert Hahn","Type of Vendor":"Assorted items","Email address":"roberthahn360@comcast.net","Type":"New","Booth":"M-28"},
{"First":"Robin","Last":"Bettencourt","Company":"Robinwood Designs","Type of Vendor":"Womens clothing and accessories","Email address":"rbettencourt@comcast.net","Type":"Returning","Booth":"R-8"},
{"First":"Robyn","Last":"Steinberger","Company":"Robyn Steinberger","Type of Vendor":"Watercolor art","Email address":"stein301@gmail.com","Type":"Returning","Booth":"M-21"},
{"First":"Bridget","Last":"Murray","Company":"Rotary Club ","Type of Vendor":"Community information","Email address":"","Type":"","Booth":"S-4"},
{"First":"Roxanne","Last":"Chardon","Company":"Roxanne Chardon","Type of Vendor":"Pastel landscapes","Email address":"chardonstudios@gmail.com","Type":"New","Booth":"M-18"},
{"First":"Rusty","Last":"Kinnunen","Company":"Rusty & Ingrid Creative Co","Type of Vendor":"Painting, printmaking","Email address":"info@rustyandingrid.com","Type":"Returning","Booth":"R-4"},
{"First":"Sharon ","Last":"DeAngelo","Company":"Sea Glass Creations","Type of Vendor":"Jewelry","Email address":"","Type":"","Booth":"S-10"},
{"First":"Sharon","Last":"Prato","Company":"Sharon Prato","Type of Vendor":"Sand dollar jewelry","Email address":"sprato@verizon.net@verizon.net","Type":"New","Booth":"R-14"},
{"First":"Stephanie","Last":"Mason","Company":"Stephanie Mason","Type of Vendor":"Fish rubbings","Email address":"","Type":"","Booth":"S-3"},
{"First":"Rich","Last":"Simons","Company":"Stonestreet Tie Dye","Type of Vendor":"Tye died clothing","Email address":"","Type":"","Booth":"T-16"},
{"First":"Raelinda","Last":"Woad","Company":"Storyteller Jewelry","Type of Vendor":"Books/ornaments/earings","Email address":"raelinda@tiac.net","Type":"Returning","Booth":"R-23"},
{"First":"Gina","Last":"Kovach","Company":"Studio G","Type of Vendor":"Jewelry","Email address":"gina.kovach@gmail.com","Type":"New","Booth":"M-14"},
{"First":"Susan","Last":"Devita","Company":"Susan Devita","Type of Vendor":"Tie dye","Email address":"","Type":"","Booth":"M-17"},
{"First":"Susan","Last":"Dodge","Company":"Susan Dodge","Type of Vendor":"Paintings","Email address":"","Type":"","Booth":"T-22"},
{"First":"Julie","Last":"Scaramella","Company":"Sunny Window","Type of Vendor":"Lavender products","Email address":"","Type":"","Booth":"R-22"},
{"First":"Jen","Last":"Jantzen","Company":"Jen Jantzen","Type of Vendor":"Dog wares","Email address":"","Type":"Returning","Booth":"R-1"},
{"First":"Teresa","Last":"Capela","Company":"Teresa Capela","Type of Vendor":"Handmade doll clothes","Email address":"teresa_capela@yahoo.com","Type":"Returning","Booth":"T-3"},
{"First":"Kelly","Last":"Williamson","Company":"The Gallery Ice Cream","Type of Vendor":"Ice cream","Email address":"","Type":"","Booth":"T-19"},
{"First":"","Last":"","Company":"7 Central","Type of Vendor":"Fine Dining","Email address":"-","Type":"-","Booth":"Food-2"},
{"First":"Steven","Last":"Manning","Company":"The Silver Spoon","Type of Vendor":"Assorted items","Email address":"thesilverspoon@comcast.net","Type":"New","Booth":"M-23"},
{"First":"Glynis","Last":"Dixon","Company":"Washed Ashore Designs","Type of Vendor":"Jewelry","Email address":"glynisdixon@yahoo.com","Type":"New","Booth":"R-12"},
{"First":"Wendy","Last":"Sullivan","Company":"Wendy Sullivan","Type of Vendor":"Face Painting","Email address":"","Type":"","Booth":"M-38"},
{"First":"Mary Ann","Last":"Wenniger","Company":"Wenniger Cottage Gallery","Type of Vendor":"Art","Email address":"","Type":"","Booth":"T-7"},
{"First":"James","Last":"Trudeau","Company":"Wheelworks Pottery","Type of Vendor":"Pottery","Email address":"jtrud3@comcast.net","Type":"Returning","Booth":"M-20"},
{"First":"Warrick","Last":"Dowsett","Company":"Wozz! Kitchen Creations","Type of Vendor":"Assorted items","Email address":"","Type":"","Booth":"M-5"}];